docto/urls.py
from django.contrib import admin
from django.urls import path, include
import dashboard.urls as dashboard
import login.urls as login
import request.urls as request
import riwayat.urls as riwayat
import daftarDokter.urls as daftarDokter

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(dashboard)),
    path('login/', include(login)),
    path('request/', include(request)),
	path('riwayat/', include(riwayat)),
	path('daftarDokter/', include(daftarDokter))
]

request/urls.py
from django.shortcuts import redirect
from django.conf.urls import url
from django.urls import path, reverse
from .views import index, insert

app_name = 'request'
urlpatterns = [
	path('', index, name="daftar"),
    path('<int:pk>/', index, name=app_name),
    path('<int:pk>/add/', insert, name="add"),
    
]

request/models.py
from django.db import models

# Create your models here.

request/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from datetime import datetime, timedelta
# Create your views here.
from django.views.decorators.http import require_http_methods

from login.forms import LoginForm
from login.models import DocToUser, Doctor, Patient, Riwayat, Spesialisasi


@login_required(login_url='/login/')
def index(request, pk=-1):
	if pk == -1:
		return redirect('/daftarDokter/')
	print(request.user)
	patient = Patient.objects.get(user=request.user)		
	response = {}
	response['saldo'] = "Rp. "+"{:,}".format(patient.saldo)+",00"
	jadwal = ""
	hari = ['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu']
	html = 'request/request.html'
	akun = DocToUser.objects.get(id=pk)
	doctor = Doctor.objects.get(user_id=akun.id)
	riwayats = Riwayat.objects.all()
	response['user'] = request.user
	response['doctor'] = doctor
	response['pk'] = pk

	waktu = datetime.strptime('09:00','%H:%M')
	for x in range(7):
		jadwal += "<tr>"
		for y in range(6):
			string = waktu.strftime('%H:%M')
			jadwal += '<td><label><input type="radio" name="waktu" value="'+str(y)+' '+string+'">'+string+'</label></td>'
		jadwal += "</tr>"
		waktu = waktu + timedelta(hours=1)
	response['jadwal'] = jadwal
	
	day = datetime.now().strftime('%d/%b/%Y')
	dt = datetime.strptime(day, '%d/%b/%Y')
	start = dt - timedelta(days=dt.weekday())
	end = start + timedelta(days=6)
	
	response['start'] = start.strftime('%d %B, %Y')
	response['end'] = end.strftime('%d %B, %Y')
	
	return render(request, html, response)

def insert(request,pk):
	print(request.method)
	if request.method == "POST":
		akun = DocToUser.objects.get(id=pk)
		doctor = Doctor.objects.get(user_id=akun.id)
		patient = Patient.objects.get(user=request.user)
		print(pk)
		print(patient)
		print(doctor)
		ke = len(Riwayat.objects.all())
		if( ke > 0 ):
			ke = Riwayat.objects.all()[ke-1].no_urut+1
		opsi = request.POST['opsi']
		saldo = patient.saldo
		delta = int(request.POST['waktu'].split(" ")[0])
		day = datetime.now().strftime('%d/%b/%Y')
		dt = datetime.strptime(day, '%d/%b/%Y')
		start = dt - timedelta(days=dt.weekday())
		date = start + timedelta(days=delta)
		date = date.strftime('%Y-%m-%d')
		print(date)

		time = request.POST['waktu'].split(" ")[1]
		try:
			Riwayat.objects.get(pasien=patient, dokter=doctor, tanggal=date, waktu=time)
			messages.error(request, "Jadwal yang anda pilih tidak tersedia !")
			return redirect('/request/'+str(pk))
		except:
			pass
		fee = getTarif(opsi)

		if (patient.saldo < fee) :
			messages.error(request, "Saldo anda kurang mencukupi dari opsi yang anda pilih.")
			return redirect('/request/'+str(pk))

		Riwayat.objects.create(no_urut=ke, pasien=patient, opsi=opsi, dokter=doctor, tanggal=date, waktu=time, tarif=fee)
		print(len(Riwayat.objects.all()))
		print("Sukses Mengirimkan Request ke Dokter!")
		messages.success(request, "Sukses Mengirimkan Request ke Dokter!")
		return redirect('/riwayat/')
	return HttpResponseRedirect(reverse('request:daftar'))

def getTarif(opsi):
	switch={
		'chat': 5000,
		'phone': 10000,
		'video': 100001
	}
	return switch[opsi]

request/templates/request/request.html
{% extends "base.html" %}
{% block content %}
<style>
	td>label{
	  cursor: pointer;
	}
	
	[type=radio]{ 
	  position: absolute;
	  opacity: 0;
	  width: 0;
	  height: 0;
	}

	/* IMAGE STYLES */
	[type=radio] + img {
	  cursor: pointer;
	  opacity : 0.4;
	  transition: all .2s ease-in-out;
	}

	/* CHECKED STYLES */
	[type=radio]:checked + img {
	  opacity : 1;
	  transform: scale(1.15); 
	}

	[type=radio]:hover + img{ 
	  transform: scale(1.15); 
	}

	.center-table th {
      text-align: center;
      vertical-align: middle;
	}

	.center-table td {
      text-align: center;
      vertical-align: middle;
	}
</style>

{% for message in messages %}
<div class="notification is-danger">
  <button class="delete" data-target=".notification"></button>
  <b>{{ message }}</b>
</div>
{% endfor %}

<form style="margin-top: 20px" id="konsul_form" action="{% url 'request:add' pk %} " method="post">
	{% csrf_token %}
	<nav class="container box">
		<input type="hidden" id="nama" name="nama" value="{{doctor.nama}}">
		<h3 class="title is-3">Pilih metode konsultasinya</h3>
		<nav class="level">
		  <div class="level-item has-text-centered">
		    <div>
		      	<label>
		      		<p class="subtitle is-6" style="margin-bottom: 10px">CHAT</p>
				  	<input type="radio" name="opsi" value="chat">
				  	<img style="height:80px; width: 80px" src="https://image.flaticon.com/icons/svg/63/63320.svg">
				</label>
		    </div>
		  </div>
		  <div class="level-item has-text-centered">
		    <div>
		      	<label>
		      		<p class="subtitle is-6" style="margin-bottom: 10px">PHONE CALL</p>
				  	<input type="radio" name="opsi" value="phone">
				  	<img style="height:80px; width: 80px" src="https://www.pngrepo.com/png/202012/170/telephone-call-phone-call.png">
				</label>	
		    </div>
		  </div>
		  <div class="level-item has-text-centered">
		    <div>
		      	<label>
		      		<p class="subtitle is-6" style="margin-bottom: 10px">VIDEO CALL</p>
				  	<input type="radio" name="opsi" value="video">
				  	<img style="height:80px; width: 80px" src="https://www.pngrepo.com/png/7798/170/videocall.png">
				</label>	
		    </div>
		  </div>
		</nav>
	</nav>
	<nav class="container box">
		<h3 class="title is-3">Pilih jadwal konsultasinya</h3>
			<nav class="level">
			  <div class="level-left">
			    <div>
			      	<label>
			      		<img style="transform: scaleX(-1); height:60px; width: 60px" src="https://image.freepik.com/icones-gratis/chevron-seta-para-a-direita-simbolo-ios-interface-de-7_318-33616.jpg">
					</label>
			    </div>
			  </div>
			  <div class="level-item has-text-centered">
			    <div>
			      	<label>
			      		<h3 class="title is-3">{{ start }} - {{ end }}</h3>
					</label>	
			    </div>
			  </div>
			  <div class="level-right">
			    <div>
				  	<img style="height:60px; width: 60px" src="https://image.freepik.com/icones-gratis/chevron-seta-para-a-direita-simbolo-ios-interface-de-7_318-33616.jpg">
			    </div>
			  </div>
			</nav>
			<table class="table is-fullwidth center-table">
				 <thead>
				   	<tr>
						<th>Senin</th>
						<th>Selasa</th>
						<th>Rabu</th>
						<th>Kamis</th>
						<th>Jumat</th>
						<th>Sabtu</th>
					</tr>
				 </thead>
				 <tbody>
				 	{{ jadwal | safe }}
				 </tbody>
			</table>
		</nav>
	</nav>
	<nav class="container has-text-centered">
		<button type="button" id="konfirm" class="button is-primary modal-button" data-target="#myModal" aria-haspopup="true" style="min-width: 120px; margin-bottom: 20px">Submit</button>		
	</nav>
</form>

<div class="modal" id="myModal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Konfirmasi</p>
      <button class="delete" id="modal-close" aria-label="close"></button>
    </header>
    <section class="modal-card-body is-capitalized">
      <!-- Content ... -->
    </section>
    <footer class="modal-card-foot">
      <button type="button" class="button is-success" id="submitForm">Submit</button>
      <button class="button" id="modal-close">Cancel</button>
    </footer>
  </div>
</div>
<script>
week = ['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu']
document.querySelectorAll('.modal-button').forEach(function(el) {
  el.addEventListener('click', function() {
    var target = document.querySelector(el.getAttribute('data-target'));
    
    target.classList.add('is-active');
    
    target.querySelectorAll('#modal-close').forEach(function(cel) {
    	cel.addEventListener('click', function() {
        	target.classList.remove('is-active');
        });
     });
  });
});

document.querySelectorAll('.notification>.delete').forEach(function(el) {
	el.addEventListener('click', function() {
	    var target = el.getAttribute('data-target');
		document.querySelector(target).remove();
		});
});

document.querySelectorAll('table').forEach(function(el) {
	el.addEventListener('click',   function() {
    	document.querySelectorAll('td').forEach(function(td) {
    		td.classList.remove('is-selected');
    	});
    	document.querySelectorAll('td>label>input[type=radio]:checked').forEach(function(td) {
    		td.parentNode.parentNode.classList.add("is-selected");
    	});
    });
});

document.querySelector('#submitForm').addEventListener('click', function() {
	document.querySelector('#konsul_form').submit();
});

document.querySelector('#konfirm').addEventListener('click', function() {
	var nama = "<b>Nama Dokter</b> : "+document.querySelector('#nama').value;
	var o_temp = document.querySelector('div>label>input[type=radio]:checked');
	if(o_temp == null){
		var opsi = '<b style="color:red">Harap pilih opsi konsultasi anda !</b>'

	} else {
		var opsi = o_temp.previousSibling.previousSibling.innerText.toLowerCase()
		opsi = opsi[0].toUpperCase() + opsi.substring(1)
		opsi = "<b>Opsi</b> : " + opsi
	}
	var j_temp = document.querySelector('td>label>input[type=radio]:checked');
	if(j_temp == null){
		hari = '<b style="color:red">Harap pilih waktu konsultasi anda !</b>'
		waktu = ''
	} else {
		var hari = parseInt(j_temp.value.split(" ")[0],10)
		hari = "<b>Hari</b> : " + week[hari]
		var waktu = "<b>Waktu</b> : " + j_temp.value.split(" ")[1]
	}
	document.querySelector('.modal-card-body').innerHTML = (nama + "<br><br>" + opsi + "<br><br>" + hari + "<br><br>" + waktu);
	
	if(o_temp == null || j_temp == null){
		document.querySelector('#submitForm').disabled = true
	} else {
		document.querySelector('#submitForm').disabled = false
	}
});
</script>
 {% endblock %}